// prisma/seedData/properties.ts

export const properties = [
  {
    title: 'Luxury Apartment',
    details: 'A spacious apartment in the heart of Kigali.',
    price: 100000,
    size: 200,
    hasParking: true,
    isForSale: true,
    isForRent: false,
    bedrooms: 3,
    bathrooms: 2,
    isSold: false,
    hasPool: true,
    appliances: ['Fridge', 'Oven'],
    yearBuilt: new Date('2010-01-01'),
    AC: true,
    YTUrl: 'https://youtu.be/example1',
    slug: 'luxury-apartment',
  },
  {
    title: 'Cozy Studio',
    details: 'A compact and cozy studio perfect for singles.',
    price: 80000,
    size: 80,
    hasParking: false,
    isForSale: false,
    isForRent: true,
    bedrooms: 1,
    bathrooms: 1,
    isSold: false,
    hasPool: false,
    appliances: ['Microwave', 'Toaster'],
    yearBuilt: new Date('2015-06-15'),
    AC: true,
    YTUrl: 'https://youtu.be/example2',
    slug: 'cozy-studio',
  },
];
